-------------
QUERY_STRING=q=a+b&s=RU&wdw=255
Search for: a b.
WE=  a : 17,  b : 17
W= a : 17 / 17, b : 17 / 17
Results 1-12 of 12.
1. [6.250%] http://site/test-abc.html <b>a</b> <b>b</b> c...
2. [6.250%] http://site/test-bac.html <b>b</b> <b>a</b> c...
3. [6.250%] http://site/test-cab.html c <b>a</b> <b>b</b>...
4. [6.250%] http://site/test-cba.html c <b>b</b> <b>a</b>...
5. [5.795%] http://site/test-aabb.html <b>A</b> o <b>A</b> o <b>B</b> o <b>B</b>...
6. [5.795%] http://site/test-abab.html <b>A</b> o <b>B</b> o <b>A</b> o <b>B</b>...
7. [5.795%] http://site/test-abba.html <b>A</b> o <b>B</b> o <b>B</b> o <b>A</b>...
8. [5.795%] http://site/test-acb.html <b>a</b> c <b>b</b>...
9. [5.795%] http://site/test-baba.html <b>B</b> o <b>A</b> o <b>B</b> o <b>A</b>...
10. [5.795%] http://site/test-bca.html <b>b</b> c <b>a</b>...
11. [3.977%] http://site/test-aaxxxb.html <b>a</b> <b>a</b> x x x <b>b</b>...
12. [3.977%] http://site/test-axxxbb.html <b>a</b> x x x <b>b</b> <b>b</b>...
-------------
QUERY_STRING=q=a+b&s=RU&wdw=0
Search for: a b.
WE=  a : 17,  b : 17
W= a : 17 / 17, b : 17 / 17
Results 1-12 of 12.
1. [6.250%] http://site/test-aabb.html <b>A</b> o <b>A</b> o <b>B</b> o <b>B</b>...
2. [6.250%] http://site/test-aaxxxb.html <b>a</b> <b>a</b> x x x <b>b</b>...
3. [6.250%] http://site/test-abab.html <b>A</b> o <b>B</b> o <b>A</b> o <b>B</b>...
4. [6.250%] http://site/test-abba.html <b>A</b> o <b>B</b> o <b>B</b> o <b>A</b>...
5. [6.250%] http://site/test-abc.html <b>a</b> <b>b</b> c...
6. [6.250%] http://site/test-acb.html <b>a</b> c <b>b</b>...
7. [6.250%] http://site/test-axxxbb.html <b>a</b> x x x <b>b</b> <b>b</b>...
8. [6.250%] http://site/test-baba.html <b>B</b> o <b>A</b> o <b>B</b> o <b>A</b>...
9. [6.250%] http://site/test-bac.html <b>b</b> <b>a</b> c...
10. [6.250%] http://site/test-bca.html <b>b</b> c <b>a</b>...
11. [6.250%] http://site/test-cab.html c <b>a</b> <b>b</b>...
12. [6.250%] http://site/test-cba.html c <b>b</b> <b>a</b>...
